version: '3.8'

services:
  api-contador:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_ENV=production
      - ARQUIVO_VISITAS=/app/data/visitas.json
      - HOST=0.0.0.0
      - PORT=5000
    restart: unless-stopped
    
  # Opcional: nginx como proxy reverso
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-contador
    restart: unless-stopped
    profiles:
      - nginx

volumes:
  data: