services:
  - type: web
    name: api-contador-visitas
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        fromService:
          type: web
          name: api-contador-visitas
          property: port
      - key: HOST
        value: 0.0.0.0
      - key: DEBUG
        value: false
      - key: FORMATO_PADRAO
        value: real
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1